### ISSUE TITLE
Reinstate local counts

### ISSUE THREAD

**Issue by petelaud** [emmadoughty/Daily_COVID-19#4]
Hi, please could you reinstate the spreadsheet of cumulative local counts of confirmed cases? Although there do appear to be some problems with data quality (e.g. Sheffield dropped from 15 to 1 yesterday), I think it's important that these issues are identifiable, because these local counts presumably form the basis for the total UK counts.

**Comment by emmadoughty** [comment]
I've left the data as provided by PHE in the COVID19_cum.csv file. I've removed my processed COVID_local.csv data file and derived plots because I feel they're misleading given the apparent data quality issues and the lack of understanding about what this means. I hope you find that approach acceptable and feel free to drop me an email (e.doughty@bham.ac.uk). It would be good to chat about the data quality issues
